apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webapp-pdb  
spec:
  minAvailable: 3     # минимум 3 пода должны быть доступны, чтобы кластер не потерял доступность
  selector:
    matchLabels:
      app: webapp   
